replicaCount: 2

image: ghcr.io/alyraffauf/aly.codes:latest@sha256:39b4d3dca56de4a7cee342465e9ac4945c086509c4659ce66788c8b62aef3c2d

hosts:
  - aly.codes
  - www.aly.codes

certificate:
  clusterIssuer: letsencrypt
  secretName: aly-codes-tls

ingress:
  enabled: false

resources:
  requests:
    cpu: 10m
    memory: 32Mi
  limits:
    cpu: 100m
    memory: 128Mi
