apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - vaultwarden-namespace.yaml
  - tranquil-pds-namespace.yaml
  - vaultwarden-env.sops.yaml
  - vaultwarden-pg-creds.sops.yaml
  - tranquil-pds-env.sops.yaml
  - tranquil-pds-sso-env.sops.yaml
  - tranquil-pds-atcr-pull.sops.yaml
  - tranquil-pg-creds.sops.yaml
  - cloudflare-api-token.sops.yaml
  - pg-shared-b2.sops.yaml
