apiVersion: ENC[AES256_GCM,data:pok=,iv:l9iB2/EczVOF9rp3leTqH342hQOriIT9PRPUTrMdRgI=,tag:d36SIakYwzDfbLwCeDg6Uw==,type:str]
data:
  SSO_OIDC_CLIENT_ID: ENC[AES256_GCM,data:wadHXoT+RnKAK3b8PV29yz+7+/cbnuB4gmACUvxcHPI0uD1E9x9igvyh27TGzirl,iv:q6MXnMR7TJkHr0mubmK+6tsHRvd/B4B9GfuLB+xSG+4=,tag:S694LXj1A+8Q8xJyhkCZGA==,type:str]
  SSO_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:3Sq5b+yUvJWKoU0S2zuikFScq2J0ldviiupOmmfMz1BXTGAmumYaAv+b5j4=,iv:vWFsKPKZ4JCEyvLoePC9NjpWuG/lKdB5HIqY2Sunxmc=,tag:aYQjililWnlS0l+lbnrGnw==,type:str]
kind: ENC[AES256_GCM,data:Q5IF8h5n,iv:xVKWwJ0WBu6SuiW+16efm7gS4nQoMlcW1naQ5UjvcmA=,tag:lK28X9FtrteEs6JHBW4TFQ==,type:str]
metadata:
  annotations:
    helm.sh/resource-policy: ENC[AES256_GCM,data:5xfsBA==,iv:ky1NzJgiv/F0DLWpkOdgdThtBLyuOCGXcCOmOrtYdOM=,tag:0WPFSw8ihl+0Htm10INyfA==,type:str]
  labels:
    app.kubernetes.io/component: ENC[AES256_GCM,data:Ngw2GyhNMg==,iv:DPAMYbxfxs4UFW5Fy3POjKURlfpfEovfWkiGvmx3J+8=,tag:VaPv5vx6i0PLm7b+e83IiQ==,type:str]
    app.kubernetes.io/managed-by: ENC[AES256_GCM,data:gejmzOmIO0UmhKlEgIgiTY+jMmHlBw==,iv:LQrq+VgPOqmkQCG8xQ4QCis/ZkUn4pS/gcHU0dIRj70=,tag:1L32PeEZLALPVfsz4vOjrg==,type:str]
  name: ENC[AES256_GCM,data:fBOy5r8DWd6uV0sT5L1+I+0ZBhk=,iv:67PSzwP0egwF278ykZJklEHMs3fUSH0UXcmBxxWuQ4U=,tag:IahwoQwdzWjgukswP5LTMA==,type:str]
  namespace: ENC[AES256_GCM,data:/VlGyBiK9JdJI8Zo,iv:yGtSqrV0xYjJOfoRYMnEt88DBv40qTZwaULuPd9QcGg=,tag:wFsJGEsFXYVjJLF02x34dw==,type:str]
type: ENC[AES256_GCM,data:6E4C4z1j,iv:JO7EzH/zwi3/iG0TUwf7mDl2NXlSokE9rC7CDNyhdAE=,tag:7hm+wOdVYKFRhhb/akgvNw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3WHlSa3VhMEpJZmoxWmVJ
        c1E0Ri9WTjN4M3ZrQnFKS0VPMS9OU01uaFhnCmRkdG96U1ZrWlludlZaMDQ0U25x
        Y0lQd1pKN2lWQ3Y5eUx6WFFGNEFGejAKLS0tIFZjVWR2eFdBczdIZnR5T0Uva0J2
        ZDlQQklOVit5Y2VrbVRnWXVsanVDbmsKOMKtLMUc1aLrBnH1+CdjG9o6WF0J3Z46
        IlfCAai4bnA0D7I2WgiYF3OZZYQf0QZ7uTvw2rS0ZpvaN9AjAsrAGw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1zj2aq2a2v3ngcer7s3jz6pufhh8ula8pw56etmy28dy25wrkk3vq59hu2s
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvbGk4cXlCck9PQ1d2ODlp
        cDNsV2tZQ2ZLQjRkUU9vdHZCNzJBRk1ubkgwCkhTbUhoM2NvMG13bnpFdjZJTXJP
        V2M1MzVXM0svbUg3Y0UzQUFqU1lLUlEKLS0tIG9QZjd4RC9YMjVlUlE1UlZpck83
        eWVoN3oyZElzZHBoY1Z3V0laVWVXYVEKECIAO8JJl4q6q7Yv2LwLPqT09POMdk2O
        x1pzaeryIPnEEFt3t5s677gz0ZRKpqzjWc067vJpxAGWQTwl7tACxw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1kny9hv9t64ge379mk977slfx8deqy3df0c4cydh0lxu4ffczkftqpe2x6g
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaVHE1a3gyci93QktycmlP
        elNPN3BWNkh2VUZGZVAxNjliYmNmOHFQQ0UwCitCREttN0ZPY0hhUGZBOTZQQS9L
        SnRCNXAvZThZVWRrWXY1eitDTlZvV0EKLS0tIDhqZmRyc2FnOFFzZy9CQ1g3YU5j
        b1NDd2NGQW9tSlNqRGVNRWVCamNFRHMKjgUQRtAybd6zji27UuFNyPLBUZWTZaWF
        p42nwdtDjhuhDSY+dQSbPvYnnF6Mc2pMnaCJMkKv/kpX4pSZacsKkA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e5a0aaueyk34klry2qk094zrwfsvga0uft93mwweye30xhqhvfzs3jgqku
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtMW8yY0tUOEtNRGRBa3FC
        NXRveG5acXpHc2ZoUjdtSnpiZG91ekZtQ0FnCmxCRHIzeDY3SUYvYTVYWlJRWDlS
        L2MvSmRqMmhFRkcweVFaZGVZdUJaMGsKLS0tIEY2ZFloaFlBY3BSZmYvTVIvMEFM
        dnNvWkVmSDFnd3l1cU01SnJZRjRMTncKlIOSQuJpFxqukAwEStrR8o+87+whMDWP
        EKdUyB9AQLneJK7Acws3tY1wQ9W9RenHZGDxcAL/EvawnEmSEEuRGA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1876lthmlfq2aq6nm6z2qyu0ed4aa5ss68xvnlw5cqxcdtzslaqrqzgcmlm
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNY1VIUVVqdlpRaWtHT2tJ
        cXFydU1pZEtzcTZEMElEdEY1dGhxYUNzNVhRCkpVa0pDdEJyZVBsRkV5Y0ljRTQw
        ZzRFMUh0TGFaNmV3eWxISVpXcmJBVHMKLS0tIDlJaFptU28xdUVxZzduZjI2QUZ6
        SnQycXROWjhwTWFsS3hEV01xaWU4WlUKnxVUSb7dyKNSsf/sjc0e/tiWcMQ541GL
        cuzaWRhmoQI5VcLBbkogCvWZ5r7Ef+JVblDWGMXn46fZCF23X/KBGQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1j9jju3whwj72udhge7v4c77gk6v6w2cq8zjngzyppwtptfsz499qyywu9a
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzNitqWkY1YkRQelVGaGVs
        V052V2lDVng0K0pBME5xL2xoMlY0QU4vQzFBCm5TeFNMUlppWnp4T2NVbklLWDNZ
        U3ZobWVhSm5LUzU0MWRBWHdYRkZUelkKLS0tIGg4OTNrMzFRL2tORVJXZXNMSWpM
        TTlwV0V1WEtNbzVWMlJBalNOM2RUdVkKapTYdbVkumTI2zEWhk2MWqDeOXwEsTYZ
        QXQUrsTW637OWiIvWwH6XY2jWDDtmoXqyG8/Lynn20lZ01/4boEkaA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age162sx8kppp90mjxw88eqs78hgnpkddf8k9kgtksmmexzvcdxknpkspmkgaf
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoc2tQUXRkNWpCN3lITVRo
        dTVFV2hpK1NEZmd3N0FXUUJxVWhCQmlCZEJRCnFxaWpnQ3I1Tm8vL0h3TFEzWGNK
        V2hoQTBQNVd1RHhYT0dsaGppNEpGU28KLS0tIFpWbUczTkpSb0d5TEsySElVRGJm
        VDlrcDBudW13UTgyNTV2WXVCUjM2TTAK5wzZRzUU91Fwk0tiFTuSYcBpwtl7w7Gz
        OSidRLKI4iUfh03UtRxFKFLXRNsdDtz7DJ9lhU0lttLgf1A5RrlTrA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1hhvzccxzrysq6ak2ktuks00vy3smr6rhey9swhncq8850epftpjqt3c7f3
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4Y0RTcVFkeTBTd1BROXNN
        TTZTQldFdDdZV1M2QUtpSi90QWJnRllFMHdFCnZDUE5qU1FuQnE2OTVXSzVZYUlV
        RmJUVG9VcHQ1Q3hRQ3BzUWZtWXpHNkEKLS0tIDVzVWtaNDBnbVkrQjFjNm9SeW1Y
        NFFXNVlya2xDOWF1WFJtSTNxQnNHMkEKM1wIRCjS2SY+Q5lJpCOBfztEWq67V98h
        aUKm9uCPBJ1jUT2R5dfNJdxIYUzyKn10/ROcikRdPG9k2Vqwa0Cg1Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age15td0jk5e2qeq2pexvxguhuuaxuaa7nhql7mhx9jr79caska6t4pqdv5spl
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByMHh0WUtjdmlkNUlHdGNU
        SWlxQlBhRC9pNmdBc0g3NExUbSs3bzVldVhjCi9YZDJOaUlsWWxkeWNGZFVSOVlU
        aVRHU0N2dWFDbHRWLy9QOURHYmhQWm8KLS0tIEp5eDZTRXhhMEM1SHlReFdub1VG
        Vko2SUhuUjJTbFYvejltLzVYL3ZwMHMKS3OizAevtAxUvRsagaTz0zgy7W/Y5eUf
        r47Itp5o7f5B86vrbdQMtowamb7zke4n8p12obJjM1WLUEH6L7hhIg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age198xvgu5frdusj6gnmducql6h634uapkcznnf704wn8wfqcumu98sttjlrc
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFa0RBNVpZU3BXRWJPdndK
        bGh0R1ZJRGdqZ0tqL1RwWFVCZlJoWTdXS3d3ClR0WlhHcm1lZ1UxY29EVFp1UEtO
        UmVWdkxwUDlEbG50cmZzdTFjUlBBODgKLS0tIC9OcU00YUNRWkdPUjRaVEtuaXp1
        cDVqV3FadzJ3VCtYa2ZyanA4VkE1aEUKCIr39UQwFc9OlhUwLcUi2tfCLnF4nrn3
        DesJ2VJ7JNNQdRhdMVDEc17MwssLfjlk+fvscD13PtLtZ8PvEuVCkg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1v4x5alkmvxsx5jsrwpecx0tne0ch2rwfkk0rq5w8x578j2pf5urssg5gx2
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0RThCZzRiWk1BcGFkWXNH
        MXMyTkM3aG9wQkVWbVg4clloZlczcjZlNWdnCmRHUDZFenBNdzUyOUhRaHlmclBh
        dForcnVqN3NBV3hndndOUHFENzNGbmsKLS0tIHg1UlNGaTQ2bkxXMENXNVpjdDFW
        MUxGVStrZTR0cTZnMUY4QWlSZVV4Uk0KVUvq9UEfCj+9T1Wi91qdILLOzBom/ypk
        DuCELJxXFfsKsnOtKbkiF9JrMHWJLPgxBN99JfHfzuHAUYzlWEqBhw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1nl6m6gpea4kxr53c35y2tp0dd26nz8jurd7058nf0fmf2wqzxu0qsdg2fk
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArZUdYd0JaMGxPU1JrbVA1
        L1ppWUNRbzB0M0N6N2I5T0RDNWFGV1VqckdVCkVWREF6MUU4dCtHbWdMRFR4WXVQ
        NTNkNEZSMDBsbkZBa0J5UG9aNjFnVm8KLS0tIDE5dDJxWGVEYzdpVlp2eTN3dmVu
        N1VwTlZJb00rOFdaRG1tMHUwUkYvbkUKdUsFwcry99NqC/nPRzoe/p3aepaAqWTp
        zcgAKryoEK9bFcavC90sodfGRlALbaxRNW3c1rXwLLRQ7hQ6EMPupg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age157en2pt286a22pxzyugt84ak6rn2at89tpma88juqfgj84lme5csq4999g
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3UUdycitRK3hQR0tlN2d4
        UWVVdlNMYUhrL3R6Q0xZd1FqSlR1L2RLK3hnCk5hWW1iQU5FVk5XbVpIWGNCV2Nh
        NXFzQmJLcmpmVis0bXhXUjJMUExMdm8KLS0tIEszeGIrcHl1YWxaU1NTaEVwSGlB
        eExKTEtnU1Z6V1lZelZFcHZVd0x6VHMKCpIsr+gnhB4+qLxuYj4Ut0wrx1i6GTWI
        aoF4BBSokgiIUh4q0y3lJ1Vt/VluYlww134WT5M/m0ZAiTdSf1Bmxg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1su5lre6favcv6gdc50yh7ecv33qgfp0tm6klunpuasa3q79kmqtsykaq0d
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnWWZSR2dmNGtuZFVzRDJm
        amVxTkxobW90eUpZNExMRTlPZU93WGVLbm1ZCjQ1T2JLMVBGbFczNzFqM1poa0Zi
        YkNCZ2dWL2xUT0t4aTBoZ09aaUk2WWsKLS0tIEJUS0NZK3ZYVTd5S1M5d2hsVWdx
        ZEpDUnhHVk54b2d4eHNndnh0ZXJMaUkKJn1YU71O4pnz4MvC61WemHpVp0fy6Ew0
        2I4TJX46YadVdEKkxhHXAqIRWUb8uvSLgYb5VVJekBf0jfHCNYp4vQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1axn36h9356ena7rq6y2xa4rcm250w9h0m9pz6x0677gla0v4f4dsj92yfm
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyY0pRb3lOSjlza0kzenEv
        eklpb3Q1emdSdFNpUkljdTVhaFBkZkY1OEg0CnV3K3pSeHZ6VGh1b0VzLzY1aFFw
        eWV3UHB5TGtCSUIyTmtRSVEvRmlKNmMKLS0tIFM2YytkRzNvOS8zNHpTdkZJWGlQ
        V1lpdVlsQVRicnh0SlNiZ09JVTlIY2MKAejnICU3nWERybPOxD94Urn/Ysl18NgA
        R5RDzDyf0cu1dClkByFATwndEGIktCI6AwrnZVXaZy/ddtMr0FgWuw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1kgp3x48wn0dmzwqp0vdpfsdw42rej0ypkj0qavs7c2t2tgdud5zqcmhl40
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQZm94a2RJMUQvSG1FQ29k
        Nm5VOWFZRklPWHJCYVVySG9tbVFaMURvT0NVClhCQmZzMFh0WWRzNmdrV01NeWZh
        Y0dVZkNMeXg0S3dwblZHdU4yMFp0VUUKLS0tIG1xNG4vNmJyVzZBcW5sWVMzeTl6
        cGNEUlRHQmkrMEZSNUJpcDNYejI5eGcKRYHAg8dx1rZGjW+sA63OiVU20Qyjy97j
        LseNUg1bQbvJRr+XUXG7bJE4+5mhdfvcm5yhrJpAA5wrwAgzEeClDw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1c62ajygt7yx5k0f85h6w3tquu4ak0gg5c9drrhh34yyyea3xtpas8knau3
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5clQ3QVZ4Ykx0TnRBaXoy
        U1JXWGlyOW1UVUFScGtlcjd3Qzd3MTNaT0NRCmpWZlUrS0NreHVqQVcxKzRxakZX
        aEZnNTNqSFdja1N3eDRGQXVhNEQxbUUKLS0tIFcxd1pFVVNBZVU5VEFTaG9TUFNZ
        QXdRekhkSXZiME9odk1DY3NHV3g3MDAKiwhrgU3FiTJeRJGdpnGvYiJ2EiNJbS/M
        q74r6fzfIZRr0sNFxOTx27zMzmf2MYK3gc9+sNLfXGPil/4MWpLYhQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1gz3835qckr54gn44znlefa6m7yvjx83gptq8keslyq944nfxsfzqndenmt
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFYVNMS2NBSGUzQWtsYWg4
        UEZJakZwYUkxMUtxU2RkeTk1Ym4rWEl0a0hjClVRVjdBWnhscmJLbER6Q3RHTTd2
        cVVsZ0V4NGFvR09aSzVoL2Z3NVczTEkKLS0tIENPN1ZxOHdXK251eFk0aVF2U253
        OUpkdmw4RzdORUpydHEwM3Mrc0R3bkEKwryc7NKC/F08W+uPiUoIbnh7UwraIVp/
        i95IFb7Ih9VX9qk4D4iC6Cpa5mWJ2eq2WtTQe7CAw/YFLl/eFV/Q8Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age195mcxysuh5yxcuvpmftsfya3xgh9m2ehusnfsxthe5k8sd4kjv6s4upyl0
  lastmodified: "2026-08-18T09:47:41Z"
  mac: ENC[AES256_GCM,data:CD0fh73MSxfNE+xt0/KKh2Q4rxwiaRaD89HLf3nFUYDEfaP+pBQhKLHbIVKIQKKmhz2KIaos96tOMtlgOtFs6lgSQ19N2UT27SVE3AaHeTv2Cs0mafpGvqjFRD2iT+46v00+hHsX1LOUBBnIBUaqBJi5J16yahKrGkZOyi4LwDI=,iv:LKEbMkE0zL9v7+x10lt94zdZCuzCWfqwkcR3/XLYJ8g=,tag:1EGMsLd7Fh+WdBIVh6r7FA==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.3
