apiVersion: ENC[AES256_GCM,data:OLM=,iv:1xvVt7MQVbQ3TCYrfvA3Hpi36w49dgGklEcQdUoN/Sw=,tag:cCezXH8zaIvE+a5STtPfoQ==,type:str]
kind: ENC[AES256_GCM,data:wH/M5iI/,iv:2sSsqcSrS4hVWrpGUs5u7oW0rb2vYjn2q9xY3k5YI3Q=,tag:tj1cz4UydJbTLCyAGl5zkg==,type:str]
metadata:
  name: ENC[AES256_GCM,data:7VKWwJTAuWO3kHuA/1J93FaSwZk=,iv:QB11CSG4wfZ737+lWRpWnrnssz+luvykyBm1Aq71rKU=,tag:Ubmv7ugb5I/m6dTUFDPMQA==,type:str]
  namespace: ENC[AES256_GCM,data:P/FkKNB35K84jqg=,iv:YhrkcLipSyqkHTq5lt69s3Ux3mXb1AJipbcyK2NieRk=,tag:wNVaLoSoV9qt2542vzOlrw==,type:str]
type: ENC[AES256_GCM,data:mTmD2Zf8zH7+icgRUhk5blWMhcFrXjy+,iv:MoZ5sXupdvqG4qZZVsTCb+DfO6lQdO9O9TpoQCiiJu4=,tag:z7N9U8FFfYwSK5jPSZwueQ==,type:str]
stringData:
  username: ENC[AES256_GCM,data:BrnMM1pozC2LVaM=,iv:DoY5FBqLP+/o7MzZxd0Es8W1wy+7bRwbiSME/hg/qiE=,tag:0FxaqVLqwqPays0IepeD/A==,type:str]
  password: ENC[AES256_GCM,data:A3U0SmuVkpmjSMSbD7L2FpWK5p6uFE3gnRcYN6pUE9xKETvu0ahZJhINWy3K77OlvKBH7Ln07757PnjmPtKWLA==,iv:uhpQ/9II6BwlsB2vFFp2MGHw7TcqsyX6u6yhO3Z8iAM=,tag:29qfsyqgoRxptCcUIaW2bw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBT1pCT1BVelR4UW95NEQw
        VytiQW9SZnErT0F6UDhMZFkwWDZ3Mml0K3h3CnNvS25tSHVNOHRYeFFpaDNWR3lO
        TFVnajFVejByNVNLVWlRQTF3OStGajAKLS0tIDFDRUM5bDNzTTBnWHJkTHI0cUFF
        VXRCVmYwWDBjQ1FYN3J1VmR4N1k0eE0KWNlif4WFif4vV3m4kNjCvhRv/5RU6mpH
        nur62TFFr65IVWys0VWFaAXNhYomliXKGxVCMEyxXgsWiNq5I5/rOw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1zj2aq2a2v3ngcer7s3jz6pufhh8ula8pw56etmy28dy25wrkk3vq59hu2s
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2Yk1TOVhYbkRHS3VBWmpk
        NE1NYjdIazczUFJGalhLSEdFZm1aVGJTZWpvCkRaeEFBdS9NKzh2TzA3dkh6WFhk
        SEZKMzZlWFo0b0pzU3Z4MHhtUjd6am8KLS0tIGp3cUhlN3oydnVQcW4zT25hNVRn
        VW1HRXZUb2lZZGUyNWNVT3RpZnNuK3MKbCFcWcDSgco5JAN79rgwb08KmG+xRY/L
        5ZYJNiuZ0qVyRZPwWGGIBh6LZCrwz6Kygj02YPVSCuqqzt6c0sd1BQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1kny9hv9t64ge379mk977slfx8deqy3df0c4cydh0lxu4ffczkftqpe2x6g
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1R3lxd1p6bk1HRVN5L0cr
        Rjd6WXRWZzlWanh1WDY0Skp4TXJsVjhEUW5zCjgrWGF5dlFtem9welgvZGU2Sy9J
        RmpMOWVWVk9OMzY4d0FycE9LQmhFcjQKLS0tICtudFBFV1MwbmVqTktkQllhTS82
        cmNIUGlSMmRlUjdHQml4bFJnTWRNZGMKSXWZTCJEYckwhePxYCegsBgiPuzmehXV
        y4E601ejYpuB7EfOivMigE29P6XfTczlikWOajYewmwuQvrXIjp5cw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e5a0aaueyk34klry2qk094zrwfsvga0uft93mwweye30xhqhvfzs3jgqku
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4YWJlTGR1alNna3o4OXFE
        dldNK3phMGhtc0hudisrNUhpeWUxOTcvVmlVCmRxbTZEL2pwUDhBeWRxSzVsckNS
        MlpXS0VoS29IY0VNZUpxbUxXQXQvbUEKLS0tIGNhR3FHVGN3b2NCbGU1NDJyeDZs
        RTU1ZlFuWWlSdEFaeWgzSzRGL1BielEKX/qYktyfi+AhadAVDhFBDQFRTd6NB+6r
        io6zjF1Y1GTjHWniN2ieiOM9wdUbS9RYIH7WBjUtusCrmD1E+0hgqg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1876lthmlfq2aq6nm6z2qyu0ed4aa5ss68xvnlw5cqxcdtzslaqrqzgcmlm
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4dzI5c1ZCajhHOVBycFFl
        TE1vUlZEaWVYbXBRdXU5TFR5Nis3ak5KWld3CjcxM1VsQ3UwY2I1bkRlamFCUkM5
        UUdKVDR4a01nQ2ppNXdLeWh5Z0hFbkUKLS0tIHhJMVhoZ0plN2hvd0RnZXI0QVl2
        VlNUTE1QTDh6RTJoYjNtcjBwaVJlbUUKyGLoW/qUwhFxuLF8RCDL7QT4NWuB/9NX
        hdzPEX2dXq3a8N0GKZxZP10ruX09xJw7jQRHb3gwe3kdwoCoLQcfqg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1j9jju3whwj72udhge7v4c77gk6v6w2cq8zjngzyppwtptfsz499qyywu9a
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwM2tXMzlJbmJyUlJQVjZJ
        UlBtdGNvT2xtdERhdThpbFdwZStqUExyUTBBCmF1WlNlM3REOHYyMUZ2akpXdWhi
        MEhsRzBidWhhV000NkZZQmFGNnZRRGsKLS0tIGtDN3lVVEN2T3hCS0Y3S1QwYlR4
        SzF1S3dUekpMM011OWdPREkwWDBwejgKaNs6wT8s3rGF8opsn/dkwbP6kcdL4Bg/
        QH5wHegB/SsjHXbmbJ4wKBb/nRL8y4CyWJH7wBmHwIeP7w0hBijKLg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age162sx8kppp90mjxw88eqs78hgnpkddf8k9kgtksmmexzvcdxknpkspmkgaf
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuZnFTcVJOMUYzRzBoaHpX
        RXhSTSszZ0dtOGFmY1Fnam11OTBhMnp2OVFZClBPQnljNGh1YWhOSGh4SWxDcnd1
        cVhzUEZ6TWgwNWdkdVlzNnJ1czRnVnMKLS0tIDlzZ0tPTFBsV3NHM3hTYm10Nms0
        SmFZMERKZXlhMU5qaUI0eHNXdkhicDQKk9yZU1vPjkkM3D/SqwSHeWdZWKb04aQR
        /hMLdOPIb0G5WIVyUAuq6Y8oLzMt2Rk1y7LEc34xTszqrjtmjlds2A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1hhvzccxzrysq6ak2ktuks00vy3smr6rhey9swhncq8850epftpjqt3c7f3
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0SlN4b0xCVFFtRGhmQ2J3
        cmZxcjJaa0lhcitSQUhkRFp6b3pCSlljM0QwCmtIanZQaXdCQi9Gd1piRE1ubmhm
        UVdtaWVMVHNjL3R3VThOTUdUVGJKL00KLS0tIGhEYW5sSTdSOGRmb3dadE56bXJ3
        Z0lmeEtDb01YbkFXOEtjV01aRjVRdEkKJIdq7oWyhb74GtQdGXY8xnvsqN8lM5rE
        8cUv6Fuv2am+u/SAC1OfNsuqSvvcsmvOg8ZAoYbVfWfWeVxw5Z5x6Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age15td0jk5e2qeq2pexvxguhuuaxuaa7nhql7mhx9jr79caska6t4pqdv5spl
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAraXd4TXV1NjlqT1hJWTdQ
        MHV3R1ZCaFFYQVdyOG5hK1Vrcjg3enhZU2d3CnF5R3JaZU9HV0JpbC9pQ2ZMU01m
        MnAvMHlSRXg5WmRqSUw3dG93WnpqWGcKLS0tIExaR0tVeTVvQy91TTBHMm1uZ1ZZ
        L2ptTXBYV01sbnBvMFFvNUw4aUNmRk0K1a6676uZeZ68LgbiRvnyd2D8zDhFCHri
        mscx6SVIByQJh9dLV2s59xOVGflMs7gBvLH+zTqwgCwHrljBCP8Bkw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age198xvgu5frdusj6gnmducql6h634uapkcznnf704wn8wfqcumu98sttjlrc
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKWFArOW5UWkFwWWFxUXZz
        SmFiSmVmZVY2VE1jdE1FZmxpUzJJQWtPRlUwCkpJT3ZJYjJTS3ZHTWVNeVJ5dXlC
        akVKSi9EN3FPQkREV3RPdzIyTXUxNTQKLS0tIGJhVndQUzAvM1k4cEpuZnIvZWNq
        S2xWYnNYMnNNMERRQ0RwTDN0dHcxckkKtpgx8gMjyUlHZWFzAFoPmpfsbEe84BzU
        Z8NBvSIuwXOc0W7zVqOnf7vUzYktgRhtsUJHaZish+002sy/k0NDUQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1v4x5alkmvxsx5jsrwpecx0tne0ch2rwfkk0rq5w8x578j2pf5urssg5gx2
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSK1RVZWtkOEdTTzNWOFdv
        eTZGck11V0NJZE1jKzZsYlZya3Y2bEtSYVJvCmdjbzFWSUNGSjcvckhtTmcwSWRQ
        bExqZGY2clB3RDlwbC9YZVRWNWZua3cKLS0tIEVlOUdocnFwMXR6dDlKd1ZTeDhF
        bGZ1S3p4bUZKYytZOUZCTzZSTHVQWVUK7Ym2+eAWOUt53Ool5VvYxhZEn55/7sIw
        bHaCZ4XoaOO4+YFeYXu2fhDDUbBo7a3PLOSZ1woPl/yEwv04wXH/sg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1nl6m6gpea4kxr53c35y2tp0dd26nz8jurd7058nf0fmf2wqzxu0qsdg2fk
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaR3NjSklTR0VxMmxBVWJn
        S3JUMWJvY1QwZHVBeG5sUG13MjZCNjFTNkNrCnFVbEU0cnk5VGIvR3BsekxvZkxD
        Z05Qb0hselV4ZFMzRGdlQVRUQkRSWTgKLS0tIHlLbjVUSHhxc1JNaTJJL1B2MWtT
        VUd4NmU2N21tSGp6WnFOTGMrTG5pdjQKdCt6OrwI23gBAWHf8OhTj0X0iYp2930y
        TcBik94CBNL0LUpDZISbqt1towgsKqi/2UAbIwBdvPL4+gh61NTm6A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age157en2pt286a22pxzyugt84ak6rn2at89tpma88juqfgj84lme5csq4999g
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMN0NZaWx3ZVNDejBsdjJs
        NDIxRGxFV1ExTmVKVWh4L25VUTE0K2ZZeGc0Ck03b01wSkRwV0FTclFSYWFZN0dw
        QjMvKzBiL1NSbElyOCs0ZWFzQlNiR1kKLS0tIHo3bnNNMis0bm5CZmY4K3pKTU9t
        alFkYWJjN2ZqajRwZFhHT0Z6a3M3a0UKQ6LmL4LNDMPEEyOV70xk42F0cobPlKrf
        D/Hv6Drx39q9PBhRIAvw4ToQneOHxQrtP+PyZdc1stZyPEmRhduiOQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1su5lre6favcv6gdc50yh7ecv33qgfp0tm6klunpuasa3q79kmqtsykaq0d
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxdlBrVUNOYkVKQ1A1QUdF
        dnloMEJtWWdSanI1Tzhma3o5UC9WVkwzVkZzClZlTG9wUERJRzlWQ2hIWDlmUlFq
        RjFWa01wNm5pMUNLL1lpRXdLcWxsdXMKLS0tIHd3QkZ4RERENFFhY0lSTUpwYS9E
        MlY3TzlYcHBmMzU4YU1WSzV6K2F3b0kKOW7eGMTHQI/pWJRSTYW/eGP/N7eqTh/4
        CcHkXxFpmWlYR8qdKXQWPyDbIhX/k1VXgG+JhpWk/Wn4wctXmiudDQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1axn36h9356ena7rq6y2xa4rcm250w9h0m9pz6x0677gla0v4f4dsj92yfm
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaYlpHSGFvMTQ1NkpraHZh
        Zmc1ajJHL05sbjVjeGJrOU5EYzhqTHBzQlNzCnluQzRKWFp0TUlnZmNGaDJxTmND
        NE1ldUdIZTN4RGk2MktJcjYzU29GQWsKLS0tIEhsSHQzUzFDV1RuajJHOExCVGNz
        Y2pmRmVpNmwzRXViRlBscER0L0VxM28KtsnE1xHIqjPe548PpIyxfbnuyqvUV+8D
        BJT56LgoOg7SiCOaCQnG5rjbmv2iPeMFv0UekR1e+001C8CTp6JMHA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1kgp3x48wn0dmzwqp0vdpfsdw42rej0ypkj0qavs7c2t2tgdud5zqcmhl40
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXRXlVblhGWVMrdE9zOTA1
        aTRwQjU4NUJLRnBzQWdXUXJMTlB0Y0pjODBzCjlSbE8wdDl1NGkrd0Ztam1BWG5w
        Z3F2bEMxZFcyU3VKa0lBYmx4eHJ1K2cKLS0tIEMwNmVaU3J0cW5nalFMdnFCMVUv
        Ym1WV0JnMjNPdXZSRlJEV1hQSEZNSmMKLvne1aLL2XIWhMD8w7WJT89dv52ce+cB
        M5xMsuO0r4KKGoDE0VmoFC3ht5jfvKjFizlD/fbIpLxvP7UNlax8LQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1c62ajygt7yx5k0f85h6w3tquu4ak0gg5c9drrhh34yyyea3xtpas8knau3
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2TUJ3U2REOUU3L0FPK0ZX
        MlZ0Q2UyWHlRRnVmSEI0eWlmc3ZoQitnSVJNCmdkOUsrTi80T21mWVJWSy9rZFZ1
        ZUpUdlRrZFdOOTJINmtMTklOVXFUb0EKLS0tIGxwMDFqdE9WTU0wZ3ZWUWpvYld0
        cVBvRktQWTJoa3l3MjRYQ2xjOGVFaWcKbxoesjticwL5yFbYhYMSau6JC6KUkgaN
        wlCVe4ifys7xSAdUA9F+yifTdhiun5BD5k+Ny1srMD5RA5hM3QpHeQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1gz3835qckr54gn44znlefa6m7yvjx83gptq8keslyq944nfxsfzqndenmt
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDOFFWOW1zZ0l0cExKNGNC
        SkFjeWpCUktzZ3NTVmQ4cDRlOGwyei8xc2tzCnVNVHpLWk1VWWYxaG5QdWNSVnN6
        d1hneHZmTUFmam5ZZElrdmhLL2FBVjQKLS0tIDlsN3ZJcWx4MVRRb29sMlJYcmVw
        OEV1aFJlQ3p6cnl2Y1d4cjlaTlFqczQK7Yd90onq4AOPcsVofbbnLPWEbcZwMwjj
        8f1ILDStBCH2w13Sc4N+5R+SZTbaNGHwQ5hdXse29bKuRscFqYH7Tg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age195mcxysuh5yxcuvpmftsfya3xgh9m2ehusnfsxthe5k8sd4kjv6s4upyl0
  lastmodified: "2026-08-18T04:37:06Z"
  mac: ENC[AES256_GCM,data:VOG8uoriosNRi+vo2ig/V3B822jL+L0dVU1l/2cGz0pMAKKFd8MQ31GIZqxNezcHkemyI/FOFxr8TsswcC4twao4TO5ob6ICG+9siofsp82R3JsA+gYUwa2zUfFlxSYamv3y3O6z/WcqQAOwigNWeft8O0bfe5+htPK+2tXqInc=,iv:nr6nusYd/UQISIWoYE+sA4W4HA9bhh/TK7WEzufxf3o=,tag:/+fbvUTMOgpt8ttQdWYShg==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.3
