apiVersion: apps/v1
kind: Deployment
metadata:
  name: aly-codes
  namespace: aly-codes
  labels:
    app: aly-codes
  annotations:
    helm.sh/resource-policy: keep
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aly-codes
  template:
    metadata:
      labels:
        app: aly-codes
    spec:
      automountServiceAccountToken: false
      enableServiceLinks: false
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: aly-codes
      containers:
        - name: aly-codes
          image: ghcr.io/alyraffauf/aly.codes:latest@sha256:39b4d3dca56de4a7cee342465e9ac4945c086509c4659ce66788c8b62aef3c2d
          ports:
            - name: http
              containerPort: 80
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 128Mi
          readinessProbe:
            httpGet:
              path: /
              port: http
          livenessProbe:
            httpGet:
              path: /
              port: http
---
apiVersion: v1
kind: Service
metadata:
  name: aly-codes
  namespace: aly-codes
  annotations:
    helm.sh/resource-policy: keep
spec:
  selector:
    app: aly-codes
  ports:
    - name: http
      port: 80
      targetPort: http
