apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tranquil-pds-valkey-data
  annotations:
    helm.sh/resource-policy: keep
  labels:
    app: tranquil-pds-valkey
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.valkey.storage.className }}
  resources:
    requests:
      storage: {{ .Values.valkey.storage.size }}
