replicaCount: 1

image: vaultwarden/server:latest@sha256:ebdfe70701c60ac0c28c697e787cea767d7972940b786037b29fe0d507f821e8
domain: https://vault.cute.haus

storage:
  className: local-path
  size: 1Gi

ingress:
  enabled: false

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 500m
    memory: 256Mi

publicIngress:
  enabled: true
  clusterIssuer: letsencrypt
  secretName: vaultwarden-tls
