replicaCount: 1

image: ghcr.io/pocket-id/pocket-id:v2@sha256:c9c1d7b70006968d673a1073df048a3fdec73ccb54e182320b56bb911340f6f1

appUrl: https://id.cute.haus

hosts:
  - id.cute.haus

certificate:
  clusterIssuer: letsencrypt
  secretName: pocket-id-tls

ingress:
  enabled: false

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: "1"
    memory: 512Mi
