apiVersion: apps/v1
kind: Deployment
metadata:
  name: skytrace
  namespace: skytrace
  labels:
    app: skytrace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: skytrace
  template:
    metadata:
      labels:
        app: skytrace
    spec:
      automountServiceAccountToken: false
      enableServiceLinks: false
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: skytrace
      containers:
        - name: skytrace
          image: ghcr.io/alyraffauf/skytrace:latest@sha256:97aa4e6627cff67abadcb8810755436bb0c3a061789ff7ff726f91a36fe868fb
          ports:
            - name: http
              containerPort: 80
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 128Mi
          readinessProbe:
            httpGet:
              path: /
              port: http
          livenessProbe:
            httpGet:
              path: /
              port: http
---
apiVersion: v1
kind: Service
metadata:
  name: skytrace
  namespace: skytrace
spec:
  selector:
    app: skytrace
  ports:
    - name: http
      port: 80
      targetPort: http
