apiVersion: apps/v1
kind: Deployment
metadata:
  name: atbbs-telnet
  namespace: atbbs
  labels:
    app: atbbs-telnet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: atbbs-telnet
  template:
    metadata:
      labels:
        app: atbbs-telnet
    spec:
      automountServiceAccountToken: false
      enableServiceLinks: false
      containers:
        - name: atbbs-telnet
          image: ghcr.io/alyraffauf/atbbs-telnet:latest@sha256:9e74409c72594b303d13f4481c881385c803b133d85590f97ba0f085c28b1521
          ports:
            - name: telnet
              containerPort: 2323
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: atbbs-telnet
  namespace: atbbs
spec:
  selector:
    app: atbbs-telnet
  ports:
    - name: telnet
      port: 2323
      targetPort: telnet
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: atbbs-telnet
  namespace: atbbs
spec:
  entryPoints:
    - telnet
  routes:
    - match: HostSNI(`*`)
      services:
        - name: atbbs-telnet
          port: 2323

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: atbbs-web
  namespace: atbbs
  labels:
    app: atbbs-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: atbbs-web
  template:
    metadata:
      labels:
        app: atbbs-web
    spec:
      automountServiceAccountToken: false
      enableServiceLinks: false
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: atbbs-web
      containers:
        - name: atbbs-web
          image: ghcr.io/alyraffauf/atbbs:latest@sha256:f0e5ff02245b1cec71d29709ded017d7edc1822a162d7d8c68df3c7769608863
          env:
            - name: PUBLIC_URL
              value: https://atbbs.aly.town
          ports:
            - name: http
              containerPort: 80
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 128Mi
          readinessProbe:
            httpGet:
              path: /
              port: http
          livenessProbe:
            httpGet:
              path: /
              port: http
---
apiVersion: v1
kind: Service
metadata:
  name: atbbs-web
  namespace: atbbs
spec:
  selector:
    app: atbbs-web
  ports:
    - name: http
      port: 80
      targetPort: http
