{{- if .Values.ingress.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vaultwarden
spec:
  secretName: {{ .Values.publicIngress.secretName }}
  issuerRef:
    kind: ClusterIssuer
    name: {{ .Values.publicIngress.clusterIssuer }}
  dnsNames:
    - {{ trimPrefix "https://" .Values.domain | quote }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vaultwarden
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - {{ trimPrefix "https://" .Values.domain | quote }}
      secretName: {{ .Values.publicIngress.secretName }}
  rules:
    - host: {{ trimPrefix "https://" .Values.domain | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vaultwarden
                port:
                  number: 80
{{- end }}
