apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Cluster capacity includes an extra PDS replica during rolling updates.
  - cluster.yaml
  - network-policy.yaml
  - vaultwarden-database.yaml
  - tranquil-database.yaml
  - scheduled-backup.yaml
  - metrics-network-policy.yaml
