apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sinnoh-public-ingress
  namespace: kube-system
spec:
  secretName: sinnoh-public-ingress-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  dnsNames:
    - aly.codes
    - www.aly.codes
    - status.aly.codes
    - switchyard.aly.codes
    - vibes.aly.codes
---
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    additionalArguments:
      - --accesslog.fields.queryparameters.defaultmode=drop
    logs:
      access:
        enabled: true
        format: json
    ports:
      telnet:
        port: 2323
        exposedPort: 23
        protocol: TCP
        expose:
          default: true
    tlsStore:
      default:
        defaultCertificate:
          secretName: sinnoh-public-ingress-tls
