replicaCount: 2

image: atcr.io/tranquil.farm/tranquil-pds:latest@sha256:9b9dc0eb4469abf9132882ebb9e762497746fe2577230a9d23d06250c7ed3378

hosts:
  - pds.cute.haus
  - aly.social
  - "*.aly.social"

publicIngress:
  enabled: false
  clusterIssuer: letsencrypt

ingress:
  enabled: true

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: "1"
    memory: 1Gi

valkey:
  storage:
    className: local-path
    size: 1Gi
  resources:
    requests:
      cpu: 25m
      memory: 128Mi
    limits:
      cpu: "1"
      memory: 512Mi
