replicaCount: 2

image: ghcr.io/alyraffauf/switchyard-website:latest@sha256:9f2b460f89c6333546e0f5fa90efa1a379a22e9917457860f462281598c5e2d4

host: switchyard.aly.codes

certificate:
  clusterIssuer: letsencrypt
  secretName: switchyard-tls

ingress:
  enabled: true

resources:
  requests:
    cpu: 10m
    memory: 32Mi
  limits:
    cpu: 100m
    memory: 128Mi
