apiVersion: apps/v1
kind: Deployment
metadata:
  name: switchyard
  namespace: switchyard
  labels:
    app: switchyard
spec:
  replicas: 2
  selector:
    matchLabels:
      app: switchyard
  template:
    metadata:
      labels:
        app: switchyard
    spec:
      automountServiceAccountToken: false
      enableServiceLinks: false
      topologySpreadConstraints:
        - maxSkew: 1
          minDomains: 2
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: switchyard
      containers:
        - name: switchyard
          image: ghcr.io/alyraffauf/switchyard-website:latest@sha256:372282c55a266d7fe43922c22845e0fb80e6fd7b0e8ced751019d7c3795acd93
          ports:
            - name: http
              containerPort: 80
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 128Mi
          readinessProbe:
            httpGet:
              path: /
              port: http
          livenessProbe:
            httpGet:
              path: /
              port: http
---
apiVersion: v1
kind: Service
metadata:
  name: switchyard
  namespace: switchyard
spec:
  selector:
    app: switchyard
  ports:
    - name: http
      port: 80
      targetPort: http
