image: ghcr.io/alyraffauf/morsels:latest@sha256:a16a51a3571deffe9c372aa604e78694c9bb1d75201ce903a4c8f19ec42a39a0

hosts:
  - morsels.blue
  - www.morsels.blue

certificate:
  clusterIssuer: letsencrypt
  secretName: morsels-blue-tls

ingress:
  enabled: false

resources:
  requests:
    cpu: 10m
    memory: 384Mi
  limits:
    cpu: "1"
    memory: 1Gi
